all:
  general:
    # for most use cases
    avatar_max_width: 100
    avatar_max_height: 100
    # for use in site header when user is logged in
    avatar_max_width2: 54
    avatar_max_height2: 54
    # for use in comments list on profile page
    avatar_max_width3: 69
    avatar_max_height3: 54
    # for use in profile page in bulletin board box
    avatar_max_width4: 188
    avatar_max_height4: 155

    avatar_folder: avatar
    avatar_default_image: anon
    avatar_default_image_type: jpg
  gallery:
    upload_folder: gallery
    valid_mime_types:
      image:
        - image/jpeg
        - image/pjpeg
        - image/gif
        - image/png
      video:
        - video/mp4
        - video/mpeg
        - video/quicktime
        - video/x-ms-wmv
    image_max_width: 600
    image_max_height: 600
    thumbnail_max_width: 40
    thumbnail_max_height: 40
  items:
    upload_folder: item
    image_large_width:  229
    image_large_height: 202
    image_thumb_width:  91
    image_thumb_height: 91
    award_price : 2
    award_limit: 0
