# default rules

avatar:
  url: /avatar/:user_id
  param: { module: profile, action: showAvatar }

profile:
  url: /profile/:username
  param: { module: profile, action: index }

gallery_image_show:
  url: /gallery/item/:id/show
  param: { module: gallery, action: itemShow }
  requirements: { id: \d+ }

homepage:
  url:   /
  param: { module: default, action: index }

default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
