<?php
// auto-generated by sfPropelCrud
// date: 2009/09/07 03:54:49
?>

<div class="body-main">

<table>
<tbody>
<tr>
<th>Id: </th>
<td><?php echo $expert_lesson->getId() ?></td>
</tr>
<tr>
<th>Title: </th>
<td><?php echo $expert_lesson->getTitle() ?></td>
</tr>
<tr>
<th>Content: </th>
<td><?php echo $expert_lesson->getContent() ?></td>
</tr>
<tr>
<th>User: </th>
<td><?php echo $expert_lesson->getUserId() ?></td>
</tr>
<tr>
<th>Price: </th>
<td><?php echo $expert_lesson->getPrice() ?></td>
</tr>
<tr>
<th>Created at: </th>
<td><?php echo $expert_lesson->getCreatedAt() ?></td>
</tr>
<tr>
<th>Updated at: </th>
<td><?php echo $expert_lesson->getUpdatedAt() ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo link_to('edit', 'expert_lesson/edit?id='.$expert_lesson->getId()) ?>
&nbsp;<?php echo link_to('list', 'expert_lesson/list') ?>

</div><!-- end of body-main -->
