<?php
// auto-generated by sfPropelCrud
// date: 2009/09/23 01:27:20
?>

<?php
  use_helper('Object');
  
  $forum_question = ForumQuestionPeer::retrieveByPK( $forum_answer->getForumQuestionId() );
?>


<?php echo form_tag('forum_answer/update') ?>

<?php echo object_input_hidden_tag($forum_answer, 'getId') ?>
<?php echo object_input_hidden_tag($forum_answer, 'getForumQuestionId') ?>

<div class="body-main">
  <div id="what-is">
    <div style="width: 30px; float: left;">
      <img height="25" width="42" alt="" src="/images/green_arrow.jpg"/>
    </div>
    <p style="font-size: 14px; color: rgb(28, 81, 124); font-weight: bold; margin-left: 55px; margin-bottom:20px">Some Fancy Shmancy Article Title Here</p>
  </div>
  <div class="qa">
    <div class="ta">
      <h1><?php echo $forum_question->getTitle(); ?></h1>
        <div class="submitted">
          <?php
            $dateToday = time();
            $dataCreation = strtotime( $forum_question->getCreatedAt() );
            $iDays = floor( ($dateToday - $dataCreation) / 86400);

            echo "Submitted $iDays day";
            echo $iDays == 1 ? '': 's';
            echo " ago!";
          ?>
        </div>
        <div class="clear"></div>
        <div class="sep"></div>
    </div><!--ta-->
    <div class="bg">
      <?php echo $forum_question->getQuestion(); ?>
    </div><!--bg-->
    <div class="b"></div>
  </div><!-- end of qa -->

  <?php
    if( UserPeer::getTypeFromIndex( $sf_user->getRaykuUser()->getType() ) == 'expert' )
    {
    ?>
      <div class="qa">
        <div class="tb">
            <h1>Record video response</h1>
              <div class="clear"></div>
              <div class="sep"></div>
          </div><!--tb-->
          <div class="answer_submit">
            <img alt="editor" src="/images/rec.png"/>
          </div><!--bg-->
          <div class="b"></div>
      </div>
      <div class="qa">
        <div class="tb">
          <h1>Preview video response</h1>
              <div class="clear"></div>
              <div class="sep"></div>
          </div><!--tb-->
          <div class="answer_submit">
            <img alt="editor" src="/images/preview.png"/>
          </div><!--bg-->
          <div class="b"></div>
      </div>
    <?php
      $sAnswerTitle = 'Additional Comments / Text Explaination';
    }
    else
    {
      $sAnswerTitle = 'Submit an answer';
    }
  ?>

  <div class="qa">
    <div class="tb">
      <h1><?php echo $sAnswerTitle; ?></h1>
        <div class="clear"></div>
        <div class="sep"></div>
    </div><!--tb-->
    <div class="answer_submit">
      <?php echo object_textarea_tag( $forum_answer, 'getAnswer', array ('size' => '67x3', 'rich' => true,
                                      'tinymce_options'=> 'theme_advanced_buttons1 : "bold,italic,underline,strikethrough, undo,redo,|,cleanup,|,bullist,numlist",
                                                           theme_advanced_buttons2 : " _ ",
                                                           theme_advanced_buttons3 : "" '
                 ) );
      ?>
    </div><!--bg-->
    <div class="b"></div>
  </div>
  
<?php echo submit_tag('save', array( 'class' => 'submit_answer') ) ?>
<?php if ($forum_answer->getId()): ?>
  &nbsp;<?php echo link_to('delete', 'forum_answer/delete?id='.$forum_answer->getId(), 'post=true&confirm=Are you sure?') ?>
<?php endif; ?>
</form>

</div><!-- end of body-main -->

<div id="boxes_right">
  <div class="box">
    <div class="t">
        <h1>Key info for question:</h1>
          <div class="div"></div>
      </div><!--t-->
      <div class="bg">
        <ul>
            <li>How to use the pentool, basics of working it</li>
            <li>How to use the pentool, basics of working it</li>
            <li>How to use the pentool, basics of working it</li>
            <li>How to use the pentool, basics of working it</li>
          </ul>
      </div><!--bg-->
      <div class="b"></div>
  </div><!--box-->
</div><!-- end of boxes_right -->