<?php
// auto-generated by sfPropelCrud
// date: 2009/09/23 01:27:20
?>

<div class="body-main">

<h1>forum_answer</h1>

<table>
<thead>
<tr>
  <th>Id</th>
  <th>Answer</th>
  <th>Forum question</th>
  <th>User</th>
  <th>Best response</th>
  <th>Created at</th>
  <th>Updated at</th>
</tr>
</thead>
<tbody>
<?php foreach ($forum_answers as $forum_answer): ?>
<tr>
    <td><?php echo link_to($forum_answer->getId(), 'forum_answer/show?id='.$forum_answer->getId()) ?></td>
      <td><?php echo $forum_answer->getAnswer() ?></td>
      <td><?php echo $forum_answer->getForumQuestionId() ?></td>
      <td><?php echo $forum_answer->getUserId() ?></td>
      <td><?php echo $forum_answer->getBestResponse() ?></td>
      <td><?php echo $forum_answer->getCreatedAt() ?></td>
      <td><?php echo $forum_answer->getUpdatedAt() ?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>

<?php echo link_to ('create', 'forum_answer/create') ?>

</div><!-- end of body-main -->