<?php
// auto-generated by sfPropelCrud
// date: 2009/09/23 01:27:20
?>

<div class="body-main">

<table>
<tbody>
<tr>
<th>Id: </th>
<td><?php echo $forum_answer->getId() ?></td>
</tr>
<tr>
<th>Answer: </th>
<td><?php echo $forum_answer->getAnswer() ?></td>
</tr>
<tr>
<th>Forum question: </th>
<td><?php echo $forum_answer->getForumQuestionId() ?></td>
</tr>
<tr>
<th>User: </th>
<td><?php echo $forum_answer->getUserId() ?></td>
</tr>
<tr>
<th>Best response: </th>
<td><?php echo $forum_answer->getBestResponse() ?></td>
</tr>
<tr>
<th>Created at: </th>
<td><?php echo $forum_answer->getCreatedAt() ?></td>
</tr>
<tr>
<th>Updated at: </th>
<td><?php echo $forum_answer->getUpdatedAt() ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo link_to('edit', 'forum_answer/edit?id='.$forum_answer->getId()) ?>
&nbsp;<?php echo link_to('list', 'forum_answer/list') ?>

</div><!-- end of body-main -->