generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      Group
    theme:            default

    list:
      display: [=name, points, created_at]
      max_per_page: 50
      filters: [name, points, created_at]
      
    edit:
      display: [name, description, points, _access]