<?php
// auto-generated by sfPropelCrud
// date: 2009/12/07 03:43:40
?>

<div class="body-main">

<h1>experts_immediate_lesson</h1>

<table>
<thead>
<tr>
  <th>Id</th>
  <th>Title</th>
  <th>Content</th>
  <th>Price</th>
  <th>User</th>
  <th>Created at</th>
  <th>Updated at</th>
</tr>
</thead>
<tbody>
<?php foreach ($experts_immediate_lessons as $experts_immediate_lesson): ?>
<tr>
    <td><?php echo link_to($experts_immediate_lesson->getId(), 'experts_immediate_lesson/show?id='.$experts_immediate_lesson->getId()) ?></td>
      <td><?php echo $experts_immediate_lesson->getTitle() ?></td>
      <td><?php echo $experts_immediate_lesson->getContent() ?></td>
      <td><?php echo $experts_immediate_lesson->getPrice() ?></td>
      <td><?php echo $experts_immediate_lesson->getUserId() ?></td>
      <td><?php echo $experts_immediate_lesson->getCreatedAt() ?></td>
      <td><?php echo $experts_immediate_lesson->getUpdatedAt() ?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>

<?php echo link_to ('create', 'experts_immediate_lesson/create') ?>

</div><!-- end of body-main -->