<?php
// auto-generated by sfPropelCrud
// date: 2009/09/16 01:48:36
?>
<?php

/**
 * classroom_forum actions.
 *
 * @package    elifes
 * @subpackage classroom_forum
 * @author     Your name here
 * @version    SVN: $Id: actions.class.php 3335 2007-01-23 16:19:56Z fabien $
 */
 
    
class classroom_forumActions extends sfActions
{
  public function executeIndex()
  {
    
  }

   
  public function executeForum()
  {
		//Grab the user
		$user = $this->getUser()->getRaykuUser();
		
		//If no forum ID was specified or the user can't access this forum
		//return an error... canAccessForum will confirm that forum_id actually 
		//points at a valid forum
				

		$this->getRequestParameter('forum_id') ;
	
		
		//Load the Forum object for the template
	
		$this->forum = ClassroomForumPeer::retrieveByPK($this->getRequestParameter('forum_id'));
		
				
		
  }
  public function executeMakethread()
	{
		
		
		if(!is_numeric($this->getRequestParameter('forum_id')))
		{
			$this->msg = 'No forum was specified... please try again.';
			return sfView::SUCCESS;
		}
		
		//If the post body wasn't set
		if($this->getRequestParameter('post_body') == '')
		{
			$this->msg = "You can't make an empty post!";
			return sfView::SUCCESS;
		}
		
			//Grab the user
		$user = $this->getUser()->getRaykuUser();
		/* @var $user User */
		
			
		//If the threadID isn't set, then the user is making a new thread
		if(!is_numeric($this->getRequestParameter('thread_id')))
		{
			//If the user hasn't given the thread a title...
			if($this->getRequestParameter('thread_title') == '')
			{
				$this->msg = 'You must specificy a title for your thread.';
				return sfView::SUCCESS;
			}
			
		
			//Create the thread
		  $thread = new ClassroomForumPost();
		  $thread->setTitle($this->getRequestParameter('thread_title'));
		  $thread->setContent($this->getRequestParameter('post_body'));
		  $thread->setPosterId($this->getUser()->getRaykuUserId());
		  $thread->setForumId($this->getRequestParameter('forum_id'));
		  
		  	if($thread->save())
		
			{
		
			//Set the message to a success message
			$this->msg = 'Thread successfully created.';
			return sfView::SUCCESS;
		
			}
		}
				
	}
	
	public function executeComment() {
	
	
		//print_r(get_class_methods(ClassroomForumThread));
		
		
		$c=new Criteria();
		$c->add(ClassroomForumPostPeer::ID ,$this->getRequestParameter('thread_id'));
		$this->thread=ClassroomForumPostPeer::doSelectOne($c);
	
	
	}
	
	public function executeMakeComment() {
	
			//Make the comment and display an error if it fails
			
			 $c = new ClassroomForumComment();
		     $c->setThreadId($this->getRequestParameter('thread_id'));
			 $c->setCommentorId($this->getUser()->getRaykuUserId());
		     $c->setContent($this->getRequestParameter('post_body'));
		     $c->setApproved('1');
		  
		  	if($c->save())
		
			{
		
				//Set the message to a success message
				$this->msg = 'Comment added successfully!';
				return sfView::SUCCESS;
		
			}
			
			
	}
	
	
}
