prod:
  rayku_url: http://rayku.com
  whiteboard_url: http://whiteboard.rayku.com
  facebook_url: http://facebook.rayku.com
  notification_bot_url : http://notification-bot.rayku.com
  bots_url : http://bots.rayku.com
  cookies_domain: .rayku.com

  g_chat_port: 8892
  fb_chat_port: 8893
  mac_server_port: 5678

  .array:
    data_cache:
      class: sfMemcacheCache
      param:
        servers:
          localhost1:
            port: 11211
            host: cache1.p.rayku.com

dev:
  rayku_url: http://rayku.dev
  facebook_url: http://facebook.rayku.dev
  whiteboard_url: http://whiteboard.rayku.dev
  notification_bot_url : http://notification-bot.rayku.dev
  bots_url : http://bots.rayku.dev
  cookies_domain: .rayku.dev

  g_chat_port: 8892
  fb_chat_port: 8893
  mac_server_port: 5678

  .array:
    data_cache:
      class: sfMemcacheCache
      param:
        servers:
          localhost1:
            port: 11211
            host: localhost 

all:
  rayku_url: http://rayku.com
  whiteboard_url: http://whiteboard.rayku.com
  facebook_url: http://facebook.rayku.com
  notification_bot_url : http://notification-bot.rayku.com
  bots_url : http://bots.rayku.com
  cookies_domain: .rayku.com

  g_chat_port: 8892
  fb_chat_port: 8893
  mac_server_port: 5678

  .array:
    data_cache:
      class: sfMemcacheCache
      param:
        servers:
          localhost1:
            port: 11211
            host: cache1.p.rayku.com
