prod:
  rayku_url: http://rayku.com
  whiteboard_url: http://whiteboard.rayku.com
  facebook_url: http://facebook.rayku.com
  notification_bot_url : http://notification-bot.rayku.com
  bots_url : http://bots.rayku.com
  cookies_domain: .rayku.com
  
  .array:
    data_cache:
      class: sfMemcacheCache
      param:
        servers:
          localhost1:
            port: 11211
            host: cache1.p.rayku.com

dev:
  rayku_url: http://rayku.dev
  facebook_url: http://facebook.rayku.dev
  whiteboard_url: http://whiteboard.rayku.dev
  notification_bot_url : http://notification-bot.rayku.dev
  bots_url : http://bots.rayku.dev
  cookies_domain: .rayku.dev

  .array:
    data_cache:
      class: sfMemcacheCache
      param:
        servers:
          localhost1:
            port: 11211
            host: 192.168.1.127 

all:
  whiteboard_url: http://whiteboard.rayku.com
  cookies_domain: .rayku.dev

  .array:
    data_cache:
      class: sfMemcacheCache
      param:
        servers:
          localhost1:
            port: 11211
            host: localhost
