dev:
  propel:
    param:
      classname: DebugPDO

test:
  propel:
    param:
      classname: DebugPDO
      dsn: 'mysql:dbname=rayku_unit_tests;host=127.0.0.1'

staging:
  propel:
    param:
      classname: DebugPDO
      dsn: 'mysql:dbname=rayku_staging;host=127.0.0.1'

all:
  propel:
    class: sfPropelDatabase
    param:
      dsn: 'mysql:dbname=rayku_db;host=db1.p.rayku.com'
      username: rayku_db
      password: UthmCRtaum34qpGL
      encoding: utf8
      persistent: true
      pooling: true
      classname: PropelPDO
