dev:
  propel:
    param:
      classname: DebugPDO

test:
  propel:
    param:
      classname:  DebugPDO

all:
  propel:
    class: sfPropelDatabase
    param:
      dsn:        mysql:dbname=rayku_db;host=localhost
      username:   rayku_db
      password:   db_*$%$%
      encoding:   utf8
      persistent: true
      pooling:    true
      classname:  PropelPDO