dev:
  propel:
    param:
      classname: DebugPDO

test:
  propel:
    param:
      classname:  DebugPDO

all:
  propel:
    class: sfPropelDatabase
    param:
      dsn:        mysql:dbname=rayku_db;host=127.0.0.1
      username:   rayku
      password:   rayku
      encoding:   utf8
      persistent: true
      pooling:    true
      classname:  PropelPDO
