<?php
// auto-generated by sfRoutingConfigHandler
// date: 2013/03/04 08:50:27
return array(
'homepage' => new sfRoute('/', array (
  'module' => 'start',
  'action' => 'index',
), array (
), array (
)),
'tos' => new sfRoute('/terms/*', array (
  'module' => 'static',
  'action' => 'tos',
), array (
), array (
)),
'about' => new sfRoute('/about/*', array (
  'module' => 'static',
  'action' => 'about',
), array (
), array (
)),
'faq' => new sfRoute('/faq/*', array (
  'module' => 'static',
  'action' => 'faq',
), array (
), array (
)),
'advertise' => new sfRoute('/advertise/*', array (
  'module' => 'static',
  'action' => 'advertise',
), array (
), array (
)),
'login' => new sfRoute('/login', array (
  'module' => 'login',
  'action' => 'index',
), array (
), array (
)),
'logout' => new sfRoute('/logout', array (
  'module' => 'login',
  'action' => 'logout',
), array (
), array (
)),
'register' => new sfRoute('/register', array (
  'module' => 'register',
  'action' => 'index',
), array (
), array (
)),
'register_confirm' => new sfRoute('/register/confirm/:code/temp/*', array (
  'module' => 'register',
  'action' => 'confirmUser',
), array (
), array (
)),
'register_confirm_mail' => new sfRoute('/register/confirmation_resend/:email', array (
  'module' => 'register',
  'action' => 'confirmationEmailResend',
), array (
), array (
  'segment_separators' => 
  array (
    0 => '/',
  ),
)),
'recover_password' => new sfRoute('/recover-password', array (
  'module' => 'login',
  'action' => 'recoverPassword',
), array (
), array (
)),
'recover_password_sent' => new sfRoute('/recover-password/sent', array (
  'module' => 'login',
  'action' => 'recoverPasswordSent',
), array (
), array (
)),
'reset_password' => new sfRoute('/reset-password/:key', array (
  'module' => 'login',
  'action' => 'resetPassword',
), array (
), array (
)),
'view_forums' => new sfRoute('/forum/*', array (
  'module' => 'forum',
  'action' => 'index',
), array (
), array (
)),
'inbox' => new sfRoute('/message/inbox/:page', array (
  'module' => 'message',
  'action' => 'list',
  'folder' => 'inbox',
  'page' => 1,
), array (
  'page' => '\\d+',
), array (
)),
'outbox' => new sfRoute('/message/outbox/:page', array (
  'module' => 'message',
  'action' => 'list',
  'folder' => 'outbox',
  'page' => 1,
), array (
  'page' => '\\d+',
), array (
)),
'compose_to' => new sfRoute('/message/compose/:nickname/*', array (
  'module' => 'message',
  'action' => 'compose',
), array (
), array (
)),
'view_group_page' => new sfRoute('/group/page/:page_id', array (
  'module' => 'cms',
  'action' => 'view',
), array (
  'page_id' => '\\d+',
), array (
)),
'edit_group_site' => new sfRoute('/group/:group_id/site/edit/', array (
  'module' => 'cms',
  'action' => 'edit',
), array (
  'group_id' => '\\d+',
), array (
)),
'group' => new sfRoute('/group/:id/page/:page', array (
  'module' => 'group',
  'action' => 'index',
  'page' => 1,
), array (
  'id' => '\\d+',
  'page' => '\\d+',
), array (
)),
'memberlist' => new sfRoute('/group/:id/memberlist/:page', array (
  'module' => 'group',
  'action' => 'memberlist',
  'page' => 1,
), array (
  'id' => '\\d+',
  'page' => '\\d+',
), array (
)),
'join_group' => new sfRoute('/group/:id/join', array (
  'module' => 'group',
  'action' => 'join',
), array (
  'id' => '\\d+',
), array (
)),
'groups' => new sfRoute('/groups', array (
  'module' => 'group',
  'action' => 'list',
), array (
), array (
)),
'profile_edit' => new sfRoute('/profile/:username/edit', array (
  'module' => 'profile',
  'action' => 'edit',
), array (
), array (
  'segment_separators' => 
  array (
    0 => '/',
  ),
)),
'profile' => new sfRoute('/profile/:username', array (
  'module' => 'profile',
  'action' => 'index',
), array (
), array (
  'segment_separators' => 
  array (
    0 => '/',
  ),
)),
'avatar' => new sfRoute('/avatar/:user_id/:size', array (
  'module' => 'profile',
  'action' => 'showAvatar',
  'size' => 1,
), array (
), array (
)),
'tutor' => new sfRoute('/tutor/:username', array (
  'module' => 'tutor',
  'action' => 'index',
), array (
), array (
  'segment_separators' => 
  array (
    0 => '/',
  ),
)),
'tutors' => new sfRoute('/tutors', array (
  'module' => 'tutors',
  'action' => 'index',
), array (
), array (
)),
'testtutor' => new sfRoute('/testtutor/:username', array (
  'module' => 'testtutor',
  'action' => 'index',
), array (
), array (
  'segment_separators' => 
  array (
    0 => '/',
  ),
)),
'training' => new sfRoute('/training', array (
  'module' => 'training',
  'action' => 'index',
), array (
), array (
)),
'regtutor_confirm' => new sfRoute('/regtutor/confirm/:code/temp/*', array (
  'module' => 'regtutor',
  'action' => 'confirmUser',
), array (
), array (
)),
'whiteboard_session_info' => new sfRoute('/session/:token', array (
  'module' => 'session',
  'action' => 'info',
), array (
), array (
)),
'whiteboard_session_id' => new sfRoute('/session/:token/chat', array (
  'module' => 'session',
  'action' => 'addChatId',
), array (
), array (
)),
'whiteboard_session_keepalive' => new sfRoute('/session/:token/keepalive', array (
  'module' => 'session',
  'action' => 'keepAlive',
), array (
), array (
)),
'default_symfony' => new sfRoute('/symfony/:action/*', array (
  'module' => 'default',
), array (
), array (
)),
'default_index' => new sfRoute('/:module', array (
  'action' => 'index',
), array (
), array (
)),
'default' => new sfRoute('/:module/:action/*', array (
), array (
), array (
)),
);
