<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2013/03/04 08:55:10
sfConfig::add(array(
  'mod_'.strtolower($moduleName).'_enabled' => true,
  'mod_'.strtolower($moduleName).'_view_class' => 'sfPHP',
  'mod_'.strtolower($moduleName).'_is_internal' => false,
));
