<?php
// auto-generated by sfPropelCrud
// date: 2009/09/04 02:27:38
?>

<?php use_helper('Object') ?>

<div id="top">
  <div class="title">
    <img alt="" src="/images/arrow-right.gif"/>
    <p>Rayku Forum Home > English Homework Help</p>
  </div>
  <select id="jumpto" onchange="return gotoforum();">
    <option value="">Quick forum selection</option>

    <?php foreach($forums as $forum): ?>
      <option value="<?php echo 'forum/'.$forum->getID() ; ?>"><?php echo $forum->getName(); ?></option>
    <?php endforeach; ?>
  </select>
</div><!-- end of top -->

<div class="spacer"></div>

<div class="body-main">
  <div class="box">

  <?php echo form_tag('forum_question/update') ?>

  <?php echo object_input_hidden_tag($forum_question, 'getId') ?>
  <?php echo object_input_hidden_tag($forum_question, 'getUserId') ?>

    <div class="top"></div>
    <div class="content">
      <div class="threadtitle">
        <h1>Create a question</h1>
          <div class="details">There's a limit of 2 active questions at any ne time!
          <br/>There's a limit of 30 questions per month!</div>
          <div class="clear-both"></div>
      </div>
      <div class="content-info">
        <h1 class="info">Question Title:</h1>
          <?php echo object_input_tag($forum_question, 'getTitle', array ('size' => 80)) ?>
          <p>This is instructive text. PLEASE make sure you search the forums BEFORE posting your question, as this will help you get a resolution quicker, aswell as not wasting the expert's time (and yur precious ammount of questions available!)</p>
          <h1 class="info" style="margin-bottom:10px">Question Content:</h1>
          <?php echo object_textarea_tag( $forum_question, 'getQuestion',
                                          array ( 'size' => '80x3',
                                                  'rich' => true,
                                                  'tinymce_options'=> 'plugins: "emotions",
                                                                       theme_advanced_buttons1 : "bold,italic,underline,strikethrough, undo,redo,|,cleanup,|,bullist,numlist",
                                                                       theme_advanced_buttons2 : " _ ",
                                                                       theme_advanced_buttons3 : "" '
                ));
          ?>
      </div>
        
<!--      <table>
      <tbody>
      <tr>
        <th>Category*:</th>

        <td>
          <?php echo select_tag( 'category_id',
                                 objects_for_select(CategoryPeer::doSelect(new Criteria()),
                                'getId', 'getName',$forum_question->getCategoryId()));
          ?>
        </td>
      </tr>

      <tr>
        <td colspan="2">
          <?php echo checkbox_tag('notify',$forum_question->getNotify(),true); ?> Send notifications
        </td>
      </tr>

      <tr>
        <th>Tags*:</th>
        <td><?php echo object_input_tag($forum_question, 'getTags', array('size' => 7,)) ?></td>
      </tr>
      </tbody>
      </table>-->
          
    </div><!--end of content -->
    <div class="spacer"></div>
    <div class="bottom"></div>
    
    <?php echo submit_tag('save', array('class' => 'question-post') ); ?>

  </form>

  <?php if ($forum_question->getId()): ?>
    &nbsp;<?php echo link_to('delete', 'forum_question/delete?id='.$forum_question->getId(), 'post=true&confirm=Are you sure?') ?>
  <?php endif; ?>

  </div><!-- end of box -->
  <div class="spacer"></div>
</div><!-- end of body-main -->

<div class="body-side">
  <a class="navlink nladd" href="#">Preview Question</a>
  <a class="navlink nladd" href="#">Post Question</a>

  <div class="box">
    <div class="top"></div>
    <div style="position: relative;" class="content">
    <div style="margin-top: 0px;" class="title"><h1>When an expert replies</h1></div>
        <div class="text">
          Choose any additional contact methods when an expert replies to your question.
          <div class="group">
            <label>SMS:</label> <input type="checkbox"/> <input type="text"/>
          </div>
          <div class="group">
            <label>E-mail:</label> <input type="checkbox"/> <input type="text"/>
          </div>
          <div class="group">
            <label>PM:</label> <input type="checkbox"/> <input type="text"/>
          </div>
        </div>
    </div>
    <div class="bottom"></div>
  </div>

  <div class="box">
    <div class="top"></div>
    <div style="position: relative;" class="content">
      <div style="margin-top: 0px;" class="title"><h1>Smileys</h1></div>
        <div class="text emoticons">
          <a href="#"><img alt="emoticon" src="images/emoticons/biggrin.png"/></a>
            <a href="#"><img alt="emoticon" src="images/emoticons/cold.gif"/></a>
            <a href="#"><img alt="emoticon" src="images/emoticons/confused.png"/></a>
            <a href="#"><img alt="emoticon" src="images/emoticons/cool.png"/></a>
            <a href="#"><img alt="emoticon" src="images/emoticons/cry.gif"/></a>
            <a href="#"><img alt="emoticon" src="images/emoticons/devil.png"/></a>
            <a href="#"><img alt="emoticon" src="images/emoticons/eek.png"/></a>
            <a href="#"><img alt="emoticon" src="images/emoticons/furious.gif"/></a>
            <a href="#"><img alt="emoticon" src="images/emoticons/giggle.gif"/></a>
            <a href="#"><img alt="emoticon" src="images/emoticons/happy.png"/></a>
            <a href="#"><img alt="emoticon" src="images/emoticons/mad.png"/></a>
            <a href="#"><img alt="emoticon" src="images/emoticons/nerd.png"/></a>
            <a href="#"><img alt="emoticon" src="images/emoticons/ninja.png"/></a>
            <a href="#"><img alt="emoticon" src="images/emoticons/poop.gif"/></a>
            <a href="#"><img alt="emoticon" src="images/emoticons/redface.png"/></a>
            <a href="#"><img alt="emoticon" src="images/emoticons/rolleyes.png"/></a>
            <a href="#"><img alt="emoticon" src="images/emoticons/skull.png"/></a>
            <a href="#"><img alt="emoticon" src="images/emoticons/sleep.gif"/></a>
            <a href="#"><img alt="emoticon" src="images/emoticons/smile.png"/></a>
            <a href="#"><img alt="emoticon" src="images/emoticons/smug.png"/></a>
            <a href="#"><img alt="emoticon" src="images/emoticons/tongue.png"/></a>
            <a href="#"><img alt="emoticon" src="images/emoticons/unsure.gif"/></a>
            <a href="#"><img alt="emoticon" src="images/emoticons/wavespin.gif"/></a>
            <a href="#"><img alt="emoticon" src="images/emoticons/wink.png"/></a>
            <a href="#"><img alt="emoticon" src="images/emoticons/timebomb.gif"/></a>
            <a href="#"><img alt="emoticon" src="images/emoticons/nerd.png"/></a>
            <a href="#"><img alt="emoticon" src="images/emoticons/inlove.gif"/></a>
            <a href="#"><img alt="emoticon" src="images/emoticons/frown.png"/></a>
          </div>
    </div>
    <div class="bottom"></div>
  </div>

  </div>

