<?php
// auto-generated by sfPropelCrud
// date: 2009/09/04 02:27:38
?>

<div class="body-main">

<table>
<tbody>
<tr>
<th>Id: </th>
<td><?php echo $forum_question->getId() ?></td>
</tr>
<tr>
<th>Title: </th>
<td><?php echo $forum_question->getTitle() ?></td>
</tr>
<tr>
<th>Question: </th>
<td><?php echo $forum_question->getQuestion() ?></td>
</tr>
<tr>
<th>Category: </th>
<td><?php echo $forum_question->getCategoryId() ?></td>
</tr>
<tr>
<th>User: </th>
<td><?php echo $forum_question->getUserId() ?></td>
</tr>
<tr>
<th>Created at: </th>
<td><?php echo $forum_question->getCreatedAt() ?></td>
</tr>
<tr>
<th>Updated at: </th>
<td><?php echo $forum_question->getUpdatedAt() ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo link_to('edit', 'forum_question/edit?id='.$forum_question->getId()) ?>
&nbsp;<?php echo link_to('list', 'forum_question/list') ?>
&nbsp;<?php echo link_to('add a comment','forum_answer/create?forum_question_id='.$forum_question->getId()) ?>

<hr />
<div>
	<?php echo count($forum_answers)." comments";?>
	<br />
	<br />
	<br />
</div>
<?php foreach($forum_answers as $forum_answer): ?>
	<div>
		<p><?php
			$user = UserPeer::retrieveByPk($forum_answer->getUserId());
			echo "by ".$user->getUsername();
		?></p>
		<p><?php echo $forum_answer->getAnswer();?> 
		
		<?php if($forum_answer->getBestResponse() == '0') :?>
				<?php echo link_to('Set as Best response','forum_question/bestResponse?ansid='.$forum_answer->getId().'&qnid='.$qnid.''); ?>
		
		<?php else: ?>
		
		       <font color="#FF0000">Best Answer</font>
						
		<?php endif; ?>
				
	
		</p>
		<br />
		<br />
		<br />
	</div>
<?php endforeach; ?>

</div><!-- end of body-main -->