generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      Gift
    theme:            default
    
    list:
      display: [_image, =name, cost, times_given]
      max_per_page: 20

    edit:
      display: [name, description, cost, image]
      fields:
        image: { type: admin_input_file_tag }