prod:
  logger:
    class: sfAggregateLogger
    param:
      level: err

cli:
  controller:
    class: sfConsoleController
  request:
    class: sfConsoleRequest
  response:
    class: sfConsoleResponse

test:
  response:
    class: sfWebResponse
    param:
      send_http_headers: false

  storage:
    class: sfSessionTestStorage
    param:
      session_path: %SF_TEST_CACHE_DIR%/sessions

all:
  storage:
    class: sfSessionStorage
    param:
      session_name: rayku_frontend
