# ----
# Static Pages
# ----
homepage:
  url:   /
  param: { module: static, action: index }

tos:
  url: /terms/*
  param: { module: static, action: tos }

about:
  url: /about/*
  param: { module: static, action: about }

faq:
  url: /faq/*
  param: { module: static, action: faq }

advertise:
  url: /advertise/*
  param: { module: static, action: advertise }

# ----
# Login & Register
# ----

login:
  url: /login
  param: { module: login, action: index }

logout:
  url: /logout
  param: { module: login, action: logout }

register:
  url: /register
  param: { module: register, action: index }

register_confirm:
  url: /register/confirm/:code/temp/*
  param: { module: register, action: confirmUser }
  skip_encoding: 
    code

recover_password:
  url: /recover-password
  param: { module: login, action: recoverPassword }

recover_password_sent:
  url: /recover-password/sent
  param: { module: login, action: recoverPasswordSent }

reset_password:
  url: /reset-password/:key
  param: { module: login, action: resetPassword }

# ----
# Forum
# ----

make_post:
  url: /forum/post/
  param: { module: forum, action: makePost }

search_thread:
  url: /forum/search/*
  param: { module: forum, action: search }

thread_status:
  url: /forum/threadstatus/:thread_id/:status/*
  param: { module: forum, action: threadstatus }

best_response:
  url: /forum/bestresponse/post_id/:post_id/:temp/*
  param: { module: forum, action: bestresponse }

view_thread:
  url: /forum/thread/:thread_id/:page/*
  param: { module: forum, action: thread, page: 1 }
  requirements: { thread_id: \d+ }

view_page:
  url: /forum/:forum_id/page/:page
  param: { module: forum, action: forum}
  requirements: { forum_id: \d+, page: \d+ }

view_forum:
  url: /forum/:forum_id/:page/*
  param: { module: forum, action: forum, page: 1 }
  requirements: { forum_id: \d+, page: \d+ }

new_thread:
  url: /forum/newthread/:forum_id/*
  param: { module: forum, action: newThread }

edit:
  url: /forum/edit/:thread_id/*
  param: { module: forum, action: edit }


expertreply_thread:
  url: /forum/expertreplythread/:forum_id/:thread_id/
  param: { module: forum, action: expertReplyThread }

userreply_thread:
  url: /forum/userreplythread/:forum_id/:thread_id/
  param: { module: forum, action: userReplyThread }



view_forums:
  url: /forum/*
  param: { module: forum, action: index }

# ----
# Private Messaging
# ----

inbox:
  url: /message/inbox/:page
  param: { module: message, action: list, folder: inbox, page: 1 }
  requirements: { page: \d+ }

outbox:
  url: /message/outbox/:page
  param: { module: message, action: list, folder: outbox, page: 1 }
  requirements: { page: \d+ }

compose_to:
  url: /message/compose/:nickname/*
  param: { module: message, action: compose }

# ----
# CMS/Groups
# ----

view_group_page:
  url: /group/page/:page_id
  param: { module: cms, action: view }
  requirements: { page_id: \d+ }

edit_group_site:
  url: /group/:group_id/site/edit/
  param: { module: cms, action: edit }
  requirements: { group_id: \d+ }

group:
  url: /group/:id/page/:page
  param: { module: group, action: index, page: 1 }
  requirements: { id: \d+, page: \d+ }

memberlist:
  url: /group/:id/memberlist/:page
  param: { module: group, action: memberlist, page: 1 }
  requirements: { id: \d+, page: \d+ }

join_group:
  url: /group/:id/join
  param: { module: group, action: join }
  requirements: { id: \d+ }

groups:
  url: /groups
  param: { module: group, action: list }


# ----
# Profile
# ----

profile_edit:
  url: /profile/:username/edit
  param: { module: profile, action: edit }
  options:
    segment_separators: ['/']

profile:
  url: /profile/:username
  param: { module: profile, action: index }
  options:
    segment_separators: ['/']

avatar:
  url: /avatar/:user_id/:size
  param: { module: profile, action: showAvatar, size: 1 }





# ----
# Tutor
# ----

tutor:
  url: /tutor/:username
  param: { module: tutor, action: index }
  options:
    segment_separators: ['/']

# ----
# Tutors
# ----

tutors:
  url: /tutors
  param: { module: tutors, action: index }


# ----
# Testtutor
# ----

testtutor:
  url: /testtutor/:username
  param: { module: testtutor, action: index }
  options:
    segment_separators: ['/']



# ----
# Training
# ----

training:
  url: /training
  param: { module: training, action: index }






# ----
# Regtutor
# ----


#regtutor:
#  url: /regtutor
#  param: { module: login, action: index }

regtutor_confirm:
  url: /regtutor/confirm/:code/temp/*
  param: { module: regtutor, action: confirmUser }


# ----
# Whiteboard session
# ----
whiteboard_session_info:
  url: /session/:token
  param: { module: session, action: info }

whiteboard_session_id:
  url: /session/:token/chat
  param: { module: session, action: addChatId }

whiteboard_session_keepalive:
  url: /session/:token/keepalive
  param: { module: session, action: keepAlive }
# ----
# Whiteboard
# ----
#whiteboard_list:
#  url: /whiteboard/*
#  param: { module: whiteboard, action: index }

#inbox:
#  url: /message/inbox/:page
#  param: { module: message, action: list, folder: inbox, page: 1 }
#  requirements: { page: \d+ }

#outbox:
#  url: /message/outbox/:page
#  param: { module: message, action: list, folder: outbox, page: 1 }
#  requirements: { page: \d+ }

#compose_to:
#  url: /message/compose/:nickname/*
#  param: { module: message, action: compose }

# ----
# Symfony
# ----

default_symfony:
  url:   /symfony/:action/*
  param: { module: default }

default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*



