default:
  http_metas:
    content-type: text/html

  metas:
    title:        Rayku.com Peer Online Tutoring
    robots:       index, follow
    language:     en

  stylesheets:    []

  javascripts:    []

  has_layout:     on
  layout:         layout