#!/bin/sh
echo "PSYBNC Creativity By ZM"
echo ""
echo "PSYBNC.SYSTEM.PORT1=$2" > psybnc.conf
echo "PSYBNC.SYSTEM.HOST1=*" >> psybnc.conf
echo "PSYBNC.HOSTALLOWS.ENTRY0=*;*" >> psybnc.conf
echo "USER0.USER.LOGIN=$1" >> psybnc.conf
echo "USER0.USER.PASS=*" >> psybnc.conf
echo "USER0.USER.RIGHTS=1" >> psybnc.conf
echo ""
cat psybnc.conf
