<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/03/04 08:48:06

return array(
'propel' => new sfPropelDatabase(array (
  'classname' => 'PropelPDO',
  'dsn' => 'mysql:dbname=rayku_db;host=db1.p.rayku.com',
  'username' => 'rayku_db',
  'password' => 'UthmCRtaum34qpGL',
  'encoding' => 'utf8',
  'persistent' => true,
  'pooling' => true,
  'name' => 'propel',
)),);
