<?php
// auto-generated by sfSecurityConfigHandler
// date: 2013/03/04 08:54:40
$this->security = array (
  'all' => 
  array (
    'is_secure' => false,
  ),
  'stepthird' => 
  array (
    'is_secure' => true,
  ),
);
