<?php
// auto-generated by sfViewConfigHandler
// date: 2013/03/04 08:53:29
$response = $this->context->getResponse();

if ($this->actionName.$this->viewName == 'searchSuccess')
{
  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());
}
else if ($this->actionName.$this->viewName == 'forumSuccess')
{
  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());
}
else if ($this->actionName.$this->viewName == 'threadSuccess')
{
  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());
}
else
{
  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());
}

if ($templateName.$this->viewName == 'searchSuccess')
{
  if (!is_null($layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout')))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else if (is_null($this->getDecoratorTemplate()) && !$this->context->getRequest()->isXmlHttpRequest())
  {
    $this->setDecoratorTemplate('' == 'layout' ? false : 'layout'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);
  $response->addMeta('title', 'Rayku.com Peer Online Tutoring', false, false);
  $response->addMeta('robots', 'index, follow', false, false);
  $response->addMeta('language', 'en', false, false);

  $response->addStylesheet('/styles/forum_global.css', '', array ());
  $response->addStylesheet('/styles/forum_donny.css', '', array ());
  $response->addStylesheet('/css/custom/forum-threads.css', '', array ());
  $response->addStylesheet('/css/custom/forum-threads-bit.css', '', array ());
  $response->addStylesheet('/css/pager.css', '', array ());
  $response->addJavascript('/sfProtoculousPlugin/js/prototype.js', '', array ());
}
else if ($templateName.$this->viewName == 'forumSuccess')
{
  if (!is_null($layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout')))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else if (is_null($this->getDecoratorTemplate()) && !$this->context->getRequest()->isXmlHttpRequest())
  {
    $this->setDecoratorTemplate('' == 'layout' ? false : 'layout'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);
  $response->addMeta('title', 'Rayku.com Peer Online Tutoring', false, false);
  $response->addMeta('robots', 'index, follow', false, false);
  $response->addMeta('language', 'en', false, false);

  $response->addStylesheet('/styles/forum_global.css', '', array ());
  $response->addStylesheet('/styles/forum_donny.css', '', array ());
  $response->addStylesheet('/css/custom/forum-threads.css', '', array ());
  $response->addStylesheet('/css/custom/forum-threads-bit.css', '', array ());
  $response->addStylesheet('/css/pager.css', '', array ());
  $response->addJavascript('/sfProtoculousPlugin/js/prototype.js', '', array ());
}
else if ($templateName.$this->viewName == 'threadSuccess')
{
  if (!is_null($layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout')))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else if (is_null($this->getDecoratorTemplate()) && !$this->context->getRequest()->isXmlHttpRequest())
  {
    $this->setDecoratorTemplate('' == 'layout' ? false : 'layout'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);
  $response->addMeta('title', 'Rayku.com Peer Online Tutoring', false, false);
  $response->addMeta('robots', 'index, follow', false, false);
  $response->addMeta('language', 'en', false, false);

  $response->addStylesheet('/styles/forum_global.css', '', array ());
  $response->addStylesheet('/styles/forum_donny.css', '', array ());
  $response->addStylesheet('/css/custom/forum-threads.css', '', array ());
  $response->addStylesheet('/css/custom/forum-threads-bit.css', '', array ());
  $response->addStylesheet('/css/pager.css', '', array ());
  $response->addJavascript('/sfProtoculousPlugin/js/prototype.js', '', array ());
}
else
{
  if (!is_null($layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout')))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else if (is_null($this->getDecoratorTemplate()) && !$this->context->getRequest()->isXmlHttpRequest())
  {
    $this->setDecoratorTemplate('' == 'layout' ? false : 'layout'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);
  $response->addMeta('title', 'Rayku.com Peer Online Tutoring', false, false);
  $response->addMeta('robots', 'index, follow', false, false);
  $response->addMeta('language', 'en', false, false);

  $response->addStylesheet('/styles/forum_global.css', '', array ());
  $response->addStylesheet('/styles/forum_donny.css', '', array ());
  $response->addStylesheet('/css/custom/forum-threads.css', '', array ());
  $response->addStylesheet('/css/custom/forum-threads-bit.css', '', array ());
  $response->addJavascript('/sfProtoculousPlugin/js/prototype.js', '', array ());
}

