<?php
// auto-generated by sfSecurityConfigHandler
// date: 2013/03/04 08:53:29
$this->security = array (
  'makepost' => 
  array (
    'is_secure' => true,
  ),
  'all' => 
  array (
    'is_secure' => false,
  ),
);
