<?php
// auto-generated by sfPropelCrud
// date: 2009/09/07 00:53:23
?>

<div class="body-main">

<?php use_helper('Object') ?>

<?php echo form_tag('expert/update') ?>

<?php echo object_input_hidden_tag($expert, 'getId') ?>

<table>
<tbody>
<tr>
  <th>Title*:</th>
  <td><?php echo object_input_tag($expert, 'getTitle', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>Description*:</th>
  <td><?php echo object_textarea_tag($expert, 'getDescription', array (
  'size' => '30x3',
)) ?></td>
</tr>
<tr>
  <th>Domain*:</th>
  <td><?php echo object_input_tag($expert, 'getDomain', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>Language*:</th>
  <td><?php echo object_input_tag($expert, 'getLanguage', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>Onlinerate:</th>
  <td><?php echo object_input_tag($expert, 'getOnlinerate', array (
  'size' => 7,
)) ?></td>
</tr>
<tr>
  <th>Emailrate:</th>
  <td><?php echo object_input_tag($expert, 'getEmailrate', array (
  'size' => 7,
)) ?></td>
</tr>
<tr>
  <th>Moc:</th>
  <td><?php echo object_input_tag($expert, 'getMoc', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>Rating*:</th>
  <td><?php echo object_input_tag($expert, 'getRating', array (
  'size' => 7,
)) ?></td>
</tr>
<tr>
  <th>User*:</th>
  <td><?php echo object_input_tag($expert, 'getUserId', array (
  'size' => 7,
)) ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo submit_tag('save') ?>
<?php if ($expert->getId()): ?>
  &nbsp;<?php echo link_to('delete', 'expert/delete?id='.$expert->getId(), 'post=true&confirm=Are you sure?') ?>
  &nbsp;<?php echo link_to('cancel', 'expert/show?id='.$expert->getId()) ?>
<?php else: ?>
  &nbsp;<?php echo link_to('cancel', 'expert/list') ?>
<?php endif; ?>
</form>

</div><!-- end of body-main -->
