<?php
// auto-generated by sfPropelCrud
// date: 2009/09/07 00:53:23
?>

<div class="body-main">

<h1>expert</h1>

<table>
<thead>
<tr>
  <th>Id</th>
  <th>Title</th>
  <th>Description</th>
  <th>Domain</th>
  <th>Language</th>
  <th>Onlinerate</th>
  <th>Emailrate</th>
  <th>Moc</th>
  <th>Rating</th>
  <th>User</th>
  <th>Created at</th>
  <th>Updated at</th>
</tr>
</thead>
<tbody>
<?php foreach ($experts as $expert): ?>
<tr>
    <td><?php echo link_to($expert->getId(), 'expert/show?id='.$expert->getId()) ?></td>
      <td><?php echo $expert->getTitle() ?></td>
      <td><?php echo $expert->getDescription() ?></td>
      <td><?php echo $expert->getDomain() ?></td>
      <td><?php echo $expert->getLanguage() ?></td>
      <td><?php echo $expert->getOnlinerate() ?></td>
      <td><?php echo $expert->getEmailrate() ?></td>
      <td><?php echo $expert->getMoc() ?></td>
      <td><?php echo $expert->getRating() ?></td>
      <td><?php echo $expert->getUserId() ?></td>
      <td><?php echo $expert->getCreatedAt() ?></td>
      <td><?php echo $expert->getUpdatedAt() ?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>

<?php echo link_to ('create', 'expert/create') ?>

</div><!-- end of body-main -->
