<?php
// auto-generated by sfPropelCrud
// date: 2009/09/07 00:53:23
?>

<div class="body-main">

<table>
<tbody>
<tr>
<th>Id: </th>
<td><?php echo $expert->getId() ?></td>
</tr>
<tr>
<th>Title: </th>
<td><?php echo $expert->getTitle() ?></td>
</tr>
<tr>
<th>Description: </th>
<td><?php echo $expert->getDescription() ?></td>
</tr>
<tr>
<th>Domain: </th>
<td><?php echo $expert->getDomain() ?></td>
</tr>
<tr>
<th>Language: </th>
<td><?php echo $expert->getLanguage() ?></td>
</tr>
<tr>
<th>Onlinerate: </th>
<td><?php echo $expert->getOnlinerate() ?></td>
</tr>
<tr>
<th>Emailrate: </th>
<td><?php echo $expert->getEmailrate() ?></td>
</tr>
<tr>
<th>Moc: </th>
<td><?php echo $expert->getMoc() ?></td>
</tr>
<tr>
<th>Rating: </th>
<td><?php echo $expert->getRating() ?></td>
</tr>
<tr>
<th>User: </th>
<td><?php echo $expert->getUserId() ?></td>
</tr>
<tr>
<th>Created at: </th>
<td><?php echo $expert->getCreatedAt() ?></td>
</tr>
<tr>
<th>Updated at: </th>
<td><?php echo $expert->getUpdatedAt() ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo link_to('edit', 'expert/edit?id='.$expert->getId()) ?>
&nbsp;<?php echo link_to('list', 'expert/list') ?>

</div><!-- end of body-main -->
